### ISSUE TITLE
Unable to Add New Role

### ISSUE THREAD

**Issue by MarkRoddy** [RyanFrantz/job-crm#3]
## Expected Behavior
Clicking the `Add Role` button will prompt me with some type of input to add information about a potential role.

## Actual Behavior
Nothing Happens. Even the click on the button, from a UI perspective doesn't appear to register that a click has happened.

## Steps to reproduced
I landed at https://jaiobee.com/, signed up for an account, Clicked the `Roles` link in the top navigation bar, and finally, I clicked the `Add Role` button.

I did so using Chrome v114.0.5735.198 on OSX.

Investigating the issue I did find this stack trace in the JS console:
![Screen Shot 2023-08-23 at 10 16 17 AM](https://github.com/RyanFrantz/jaiobee/assets/346362/3f67aa41-bea5-4e83-8f01-985fad1ae72e)

**Comment by MarkRoddy** [comment]
FWIW, I've retried my steps to reproduce, and I'm no longer seeing the issue. I was able to add a role. So... maybe it was a fluke?

**Comment by RyanFrantz** [comment]
That _is_ really odd. I'm not sure what `tabPrompt.js` is, but I know for sure it's not part of `jaiobee`.

@MarkRoddy Have you experienced this since you last successfully added a role?

**Comment by MarkRoddy** [comment]
I've tried a few things just now to see if I can reproduce it:
1. Log out and back in.
2. Create a new account.
3. Hard refresh the page to trigger a reload of JS sources (was wondering if this was an ordering issue).
4. Created a new account in Safari.

None of them reproduced the issue. So... maybe everything's fine?

**Comment by RyanFrantz** [comment]
Closing this issue.
